name: weather_application
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
#  location: ^8.0.0
  geolocator: ^13.0.2
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  equatable: ^2.0.7
  provider: ^6.1.2
  carousel_slider: ^5.0.0
  timezone: ^0.9.1
  fl_chart: ^0.68.0
  #  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4

flutter:
  assets:
    - assets/images/
    - assets/icons/
  # everytime when add new assets run:
  # flutter clean
  # flutter pub get
  # flutter run
  uses-material-design: true